### ISSUE TITLE
can't  import  go-graphql-mongodb-boilerplate/generated/gqlgen

### ISSUE THREAD

**Issue by Origin-zhao** [kazmerdome/go-gqlgen-mongo-driver-boilerplate#1]
can't  import  go-graphql-mongodb-boilerplate/generated/gqlgen

**Comment by kazmerdome** [comment]
Hey, Thanks for the issue!
The 'make generate' command will generate all of the GQL assets into the generated folder!
I will extend the readme.md development mode/step3 with the command!

**Comment by Origin-zhao** [comment]
> Hey, Thanks for the issue!
> The 'make generate' command will generate all of the GQL assets into the generated folder!
> I will extend the readme.md development mode/step3 with the command!

thinks for this， it's work!
i use the command ‘go run hack/gqlgen-generator.go’
